/**
 * Browser worker entry. Imported by MswProvider only when MSW is enabled
 * for the current environment (dev or NEXT_PUBLIC_MSW=1).
 *
 * The shipped public/mockServiceWorker.js is generated by `npx msw init`
 * and lives at the site root.
 */
import { setupWorker } from 'msw/browser';
import { handlers } from './handlers';

export const worker = setupWorker(...handlers);
