"""Threaded AI assistant — per-Module conversation, streamed responses, tool calls.

Threads are keyed by Module ID (the human-readable serial / barcode the lab
sticks on the panel — e.g. ``MOD-2026-001``). A single thread spans the full
test lifecycle for that module: Setup -> Live Monitor -> Data -> Analysis ->
Report across all 7 IEC test tabs. The assistant can pull run metadata, slice
telemetry, recompute Gate-2 analysis, and recommend a pass/fail verdict via
four explicit tool calls.

Storage
-------
The existing ``ai_thread`` table is reused without a migration: the string
Module ID is encoded into ``title`` as ``module:<id>`` so we can look threads
up with a single equality query. ``messages`` (JSON) holds the full
transcript as ``{role, content, ts, tool_calls?, tool_results?}`` entries.

Streaming
---------
``POST /api/assistant/threads/{module_id}/messages`` returns a
``text/event-stream`` (SSE). Events:

* ``meta``         — once at the start: thread id, model, demo flag.
* ``tool_call``    — name + args of a tool the assistant is invoking.
* ``tool_result``  — compact result payload from the tool.
* ``token``        — a chunk of the final assistant text.
* ``done``         — terminator with the persisted message id.
* ``error``        — bail-out reason; the user message is still persisted.

Tool routing
------------
Routing is deterministic and offline-friendly so tests pass without network
access:

* mention of "run", "session", "history" or a TR-ID  -> ``get_run``
* "telemetry", "samples", "last N readings"          -> ``query_telemetry``
* "analysis", "delta", "pmax", "gate"                -> ``recompute_analysis``
* "pass", "fail", "verdict", "recommend"             -> ``suggest_pass_fail``

If ``ANTHROPIC_API_KEY`` is set, the synthesized answer text is generated by
Claude with the same tool results pre-resolved and injected into the prompt;
otherwise a templated narrative is streamed. Either path produces the same
SSE event shape, so the client code is unchanged.
"""
from __future__ import annotations

import asyncio
import json
import os
import re
import time
from contextlib import contextmanager
from datetime import datetime
from typing import Any, AsyncIterator, Callable, Dict, Iterable, Iterator, List, Optional, Tuple

from fastapi import APIRouter, HTTPException, Path
from fastapi.responses import StreamingResponse
from pydantic import BaseModel, Field
from sqlmodel import Session, select

try:
    from .db.models import AIThread, TelemetrySample, TestRun
    from .db.session import get_session
except ImportError:  # pragma: no cover - script-mode fallback
    from db.models import AIThread, TelemetrySample, TestRun  # type: ignore[no-redef]
    from db.session import get_session  # type: ignore[no-redef]


# --- Gate-2 threshold mirrors frontend/types/test-session.ts ---------------
GATE2_PMAX_DELTA_PERCENT = -5.0

# --- Title scheme used to key threads on Module ID ------------------------
THREAD_TITLE_PREFIX = "module:"

# Pattern to recognise TestRun ids spoken inline (e.g. "TR-42").
_RUN_ID_RE = re.compile(r"\b(?:TR|RUN|TR#|TR-)\s*[-:#]?\s*(\d{1,9})\b", re.IGNORECASE)


# ===========================================================================
# Pydantic schemas
# ===========================================================================
class AssistantMessage(BaseModel):
    role: str = Field(pattern="^(user|assistant|system)$")
    content: str
    ts: float
    tool_calls: Optional[List[Dict[str, Any]]] = None
    tool_results: Optional[List[Dict[str, Any]]] = None


class ThreadOut(BaseModel):
    module_id: str
    thread_id: int
    created_at: datetime
    updated_at: datetime
    messages: List[AssistantMessage]


class SendMessageBody(BaseModel):
    message: str = Field(min_length=1, max_length=4000)
    # Optional context the UI may pass — current sub-tab, recent reading,
    # whatever helps the model. Never trusted as authoritative.
    context: Optional[Dict[str, Any]] = None
    # If the operator pinned a particular run to the chat — usually the run
    # currently visible in Live Monitor or Analysis sub-tab.
    test_run_id: Optional[int] = None


# ===========================================================================
# Thread store — thin wrapper around AIThread/messages JSON
# ===========================================================================
def _thread_title(module_id: str) -> str:
    return f"{THREAD_TITLE_PREFIX}{module_id}"


def _normalise_module_id(module_id: str) -> str:
    """Strip whitespace, enforce a length sane for a barcode/serial label.

    Empty values are rejected with HTTP 400 by the caller; we return the
    cleaned value so the title is stable across whitespace variations.
    """
    cleaned = (module_id or "").strip()
    if not cleaned or len(cleaned) > 128:
        raise HTTPException(status_code=400, detail="invalid module_id")
    return cleaned


def _ensure_messages_list(thread: AIThread) -> List[Dict[str, Any]]:
    """Coerce the JSON column into the canonical ``[{...}, ...]`` shape.

    Legacy rows stored ``{"m": [...]}`` (see ``test_db_models.py``); we
    normalise on read so callers see one shape only.
    """
    raw = thread.messages or {}
    if isinstance(raw, list):
        return list(raw)
    if isinstance(raw, dict):
        for key in ("messages", "items", "m"):
            v = raw.get(key)
            if isinstance(v, list):
                return list(v)
    return []


def get_or_create_thread(session: Session, module_id: str) -> AIThread:
    title = _thread_title(module_id)
    existing = session.exec(select(AIThread).where(AIThread.title == title)).first()
    if existing is not None:
        return existing
    thread = AIThread(title=title, messages={"messages": []})
    session.add(thread)
    session.commit()
    session.refresh(thread)
    return thread


def append_messages(session: Session, thread: AIThread, new_msgs: Iterable[Dict[str, Any]]) -> AIThread:
    msgs = _ensure_messages_list(thread)
    msgs.extend(new_msgs)
    thread.messages = {"messages": msgs}
    thread.updated_at = datetime.utcnow()
    session.add(thread)
    session.commit()
    session.refresh(thread)
    return thread


def clear_thread(session: Session, module_id: str) -> bool:
    title = _thread_title(module_id)
    existing = session.exec(select(AIThread).where(AIThread.title == title)).first()
    if existing is None:
        return False
    existing.messages = {"messages": []}
    existing.updated_at = datetime.utcnow()
    session.add(existing)
    session.commit()
    return True


# ===========================================================================
# Tool implementations
# ===========================================================================
def _serialise_run(run: TestRun) -> Dict[str, Any]:
    return {
        "id": run.id,
        "test_type": run.test_type,
        "standard": run.standard,
        "mqt": run.mqt,
        "status": run.status.value if hasattr(run.status, "value") else str(run.status),
        "module_id": run.module_id,
        "operator_id": run.operator_id,
        "equipment_id": run.equipment_id,
        "started_at": run.started_at.isoformat() if run.started_at else None,
        "ended_at": run.ended_at.isoformat() if run.ended_at else None,
        "sample_count": run.sample_count,
        "csv_path": run.csv_path,
        "params": run.params,
        "result": run.result,
    }


def tool_get_run(
    session: Session,
    *,
    test_run_id: Optional[int] = None,
    module_id: Optional[str] = None,
    limit: int = 5,
) -> Dict[str, Any]:
    """Return one TestRun by id, or up to ``limit`` recent runs for the module."""
    if test_run_id is not None:
        run = session.get(TestRun, test_run_id)
        if run is None:
            return {"found": False, "test_run_id": test_run_id}
        return {"found": True, "run": _serialise_run(run)}

    if module_id is None:
        return {"found": False, "error": "neither test_run_id nor module_id provided"}

    # Lookup the numeric module FK via serial_no on Module — but to stay
    # decoupled from the Module table here, accept either: (a) the human
    # serial used by the UI, or (b) a numeric module FK. For (a) we filter
    # by Module.serial_no in a join-style query.
    from .db.models import Module  # local import to avoid cycles

    rows: List[TestRun] = []
    try:
        # Try as numeric Module.id first.
        as_int = int(module_id)
        rows = list(
            session.exec(
                select(TestRun)
                .where(TestRun.module_id == as_int)
                .order_by(TestRun.started_at.desc())
                .limit(limit)
            )
        )
    except (TypeError, ValueError):
        rows = []

    if not rows:
        mod = session.exec(select(Module).where(Module.serial_no == module_id)).first()
        if mod and mod.id is not None:
            rows = list(
                session.exec(
                    select(TestRun)
                    .where(TestRun.module_id == mod.id)
                    .order_by(TestRun.started_at.desc())
                    .limit(limit)
                )
            )

    return {"found": bool(rows), "module_id": module_id, "runs": [_serialise_run(r) for r in rows]}


def tool_query_telemetry(
    session: Session, *, test_run_id: int, last_n: int = 20
) -> Dict[str, Any]:
    """Return the ``last_n`` most-recent telemetry samples for a run."""
    last_n = max(1, min(int(last_n), 1000))
    rows = list(
        session.exec(
            select(TelemetrySample)
            .where(TelemetrySample.test_run_id == test_run_id)
            .order_by(TelemetrySample.ts.desc())
            .limit(last_n)
        )
    )
    rows.reverse()  # chronological for downstream consumers
    return {
        "test_run_id": test_run_id,
        "count": len(rows),
        "samples": [
            {
                "ts": s.ts.isoformat(),
                "step": s.step_no,
                "v": s.voltage,
                "i": s.current,
                "p": s.power,
                "t": s.temperature,
            }
            for s in rows
        ],
    }


def tool_recompute_analysis(
    session: Session, *, test_run_id: int
) -> Dict[str, Any]:
    """Recompute the Gate-2 ΔPmax for a run from its telemetry samples.

    Mirrors ``frontend/components/AnalysisPanel.tsx`` so the UI and the
    assistant agree on the same number. Falls back to the run's stored
    ``result`` dict if telemetry is missing.
    """
    samples = list(
        session.exec(
            select(TelemetrySample)
            .where(TelemetrySample.test_run_id == test_run_id)
            .order_by(TelemetrySample.ts.asc())
        )
    )
    powers = [s.power for s in samples if s.power is not None]
    if len(powers) < 2:
        run = session.get(TestRun, test_run_id)
        if run is None:
            return {"test_run_id": test_run_id, "error": "run not found"}
        result = run.result or {}
        return {
            "test_run_id": test_run_id,
            "source": "stored_result",
            "pre_pmax_w": result.get("pre_pmax_w"),
            "post_pmax_w": result.get("post_pmax_w"),
            "delta_pmax_pct": result.get("delta_pmax_pct"),
            "gate2_threshold_pct": GATE2_PMAX_DELTA_PERCENT,
            "pass": result.get("pass"),
            "sample_count": len(samples),
        }
    pre, post = powers[0], powers[-1]
    delta = ((post - pre) / pre) * 100.0 if pre else 0.0
    return {
        "test_run_id": test_run_id,
        "source": "telemetry",
        "pre_pmax_w": pre,
        "post_pmax_w": post,
        "peak_pmax_w": max(powers),
        "avg_pmax_w": sum(powers) / len(powers),
        "delta_pmax_pct": round(delta, 4),
        "gate2_threshold_pct": GATE2_PMAX_DELTA_PERCENT,
        "pass": delta >= GATE2_PMAX_DELTA_PERCENT,
        "sample_count": len(samples),
    }


def tool_suggest_pass_fail(
    session: Session, *, test_run_id: int
) -> Dict[str, Any]:
    """Combine recompute_analysis + the run's stored verdict and emit a
    recommendation with a short justification suitable for an operator note."""
    analysis = tool_recompute_analysis(session, test_run_id=test_run_id)
    if analysis.get("error"):
        return {"test_run_id": test_run_id, "recommendation": None, "reason": analysis["error"]}
    delta = analysis.get("delta_pmax_pct")
    stored_pass = analysis.get("pass")
    if delta is None:
        return {
            "test_run_id": test_run_id,
            "recommendation": "INDETERMINATE",
            "confidence": 0.0,
            "reason": "Insufficient telemetry to compute ΔPmax.",
        }
    margin = float(delta) - GATE2_PMAX_DELTA_PERCENT
    if stored_pass is None:
        verdict = "PASS" if margin >= 0 else "FAIL"
    else:
        verdict = "PASS" if stored_pass else "FAIL"
    # Confidence: 1.0 at >= 2% margin in either direction, scaled linearly.
    confidence = max(0.0, min(1.0, abs(margin) / 2.0))
    reason = (
        f"ΔPmax = {delta:.2f}% vs Gate-2 floor of {GATE2_PMAX_DELTA_PERCENT:.1f}%; "
        f"margin = {margin:+.2f} pts."
    )
    return {
        "test_run_id": test_run_id,
        "recommendation": verdict,
        "confidence": round(confidence, 3),
        "delta_pmax_pct": delta,
        "gate2_threshold_pct": GATE2_PMAX_DELTA_PERCENT,
        "reason": reason,
    }


# ===========================================================================
# Routing — decide which tools to invoke for a given user message
# ===========================================================================
ToolName = str  # "get_run" | "query_telemetry" | "recompute_analysis" | "suggest_pass_fail"


def _extract_run_id(text: str) -> Optional[int]:
    m = _RUN_ID_RE.search(text)
    if not m:
        return None
    try:
        return int(m.group(1))
    except ValueError:
        return None


def plan_tool_calls(
    message: str, *, default_run_id: Optional[int], module_id: str
) -> List[Dict[str, Any]]:
    """Return an ordered list of {name, args} tool calls inferred from intent.

    Always emits at least one call so the operator gets something useful even
    on a bare ``hello``.
    """
    ml = message.lower()
    run_id = _extract_run_id(message) or default_run_id
    plan: List[Dict[str, Any]] = []

    wants_verdict = any(k in ml for k in ("pass", "fail", "verdict", "recommend", "should we"))
    wants_analysis = any(k in ml for k in ("delta", "pmax", "gate", "analysis", "degrad"))
    wants_telemetry = any(k in ml for k in ("telemetry", "samples", "readings", "last ", "latest"))
    wants_run = any(k in ml for k in ("run", "session", "history", "status", "module")) or run_id is not None

    specific_runnable = (wants_verdict or wants_analysis or wants_telemetry) and run_id is not None

    # Always include get_run when chitchat OR no run-specific call will run.
    # This guarantees the operator gets at least one answer per turn.
    if wants_run or not specific_runnable:
        plan.append({
            "name": "get_run",
            "args": {"test_run_id": run_id, "module_id": module_id, "limit": 5},
        })

    if wants_telemetry and run_id is not None:
        # parse "last 50" / "last 100" if present
        n_match = re.search(r"last\s+(\d{1,4})", ml)
        last_n = int(n_match.group(1)) if n_match else 20
        plan.append({
            "name": "query_telemetry",
            "args": {"test_run_id": run_id, "last_n": last_n},
        })

    if wants_analysis and run_id is not None:
        plan.append({"name": "recompute_analysis", "args": {"test_run_id": run_id}})

    if wants_verdict and run_id is not None:
        plan.append({"name": "suggest_pass_fail", "args": {"test_run_id": run_id}})

    return plan


TOOL_DISPATCH: Dict[ToolName, Callable[..., Dict[str, Any]]] = {
    "get_run": tool_get_run,
    "query_telemetry": tool_query_telemetry,
    "recompute_analysis": tool_recompute_analysis,
    "suggest_pass_fail": tool_suggest_pass_fail,
}


def run_tool(session: Session, name: str, args: Dict[str, Any]) -> Dict[str, Any]:
    fn = TOOL_DISPATCH.get(name)
    if fn is None:
        return {"error": f"unknown tool: {name}"}
    # Filter args to the function's accepted kwargs (defensive against UI drift)
    clean = {k: v for k, v in args.items() if v is not None}
    try:
        return fn(session, **clean)
    except TypeError as exc:
        return {"error": f"bad args for {name}: {exc}"}
    except Exception as exc:  # pragma: no cover - logged but never crashes the stream
        return {"error": f"{type(exc).__name__}: {exc}"}


# ===========================================================================
# Narrative synthesis (deterministic — offline default)
# ===========================================================================
def _summarise_tool_results(
    message: str, tool_results: List[Dict[str, Any]], module_id: str
) -> str:
    """Turn tool outputs into a short operator-friendly briefing.

    The shape mirrors the operator runbook: state the module + scope, give
    the most decision-relevant number, then close with the verdict if known.
    """
    lines: List[str] = []
    lines.append(f"Module {module_id} — re: \"{message.strip()[:120]}\"")

    for call in tool_results:
        name = call.get("name")
        out = call.get("result", {})
        if name == "get_run":
            if out.get("found") and out.get("run"):
                r = out["run"]
                lines.append(
                    f"• Pinned run TR-{r['id']} ({r['test_type'].upper()} · "
                    f"{r.get('standard') or '—'}) is **{r['status']}**, "
                    f"{r.get('sample_count', 0)} samples."
                )
            elif out.get("found") and out.get("runs"):
                runs = out["runs"]
                lines.append(f"• {len(runs)} recent run(s) for this module:")
                for r in runs[:3]:
                    lines.append(
                        f"   – TR-{r['id']} {r['test_type'].upper()} "
                        f"{r['status']} ({r.get('sample_count', 0)} samples)"
                    )
            else:
                lines.append("• No matching run found.")
        elif name == "query_telemetry":
            n = out.get("count", 0)
            if n:
                last = out["samples"][-1]
                lines.append(
                    f"• Telemetry: last {n} samples; latest V={last.get('v')} "
                    f"I={last.get('i')} P={last.get('p')} T={last.get('t')}."
                )
            else:
                lines.append("• Telemetry: no samples yet for this run.")
        elif name == "recompute_analysis":
            delta = out.get("delta_pmax_pct")
            if delta is None:
                lines.append("• Analysis: not enough samples to compute ΔPmax.")
            else:
                lines.append(
                    f"• Analysis: ΔPmax = {delta:.2f}% vs Gate-2 floor "
                    f"{out.get('gate2_threshold_pct')}% — "
                    f"{'PASS' if out.get('pass') else 'FAIL'}."
                )
        elif name == "suggest_pass_fail":
            rec = out.get("recommendation")
            if rec:
                lines.append(
                    f"• Recommendation: **{rec}** "
                    f"(confidence {out.get('confidence', 0):.0%}). {out.get('reason', '')}"
                )
            else:
                lines.append(f"• Recommendation withheld: {out.get('reason', 'no data')}.")
        else:
            lines.append(f"• {name}: {json.dumps(out)[:200]}")

    if len(lines) == 1:
        lines.append("• No tools matched this query. Try mentioning a TR id, telemetry, ΔPmax, or pass/fail.")

    return "\n".join(lines)


# ===========================================================================
# SSE streaming
# ===========================================================================
def _sse(event: str, data: Any) -> str:
    payload = data if isinstance(data, str) else json.dumps(data, default=str)
    # Multi-line data fields must be prefixed line-by-line per the SSE spec.
    data_lines = "\n".join(f"data: {line}" for line in payload.splitlines() or [""])
    return f"event: {event}\n{data_lines}\n\n"


def _chunk_text(text: str, target_chars: int = 60) -> Iterator[str]:
    """Yield text in pseudo-token chunks so the client UI animates a stream."""
    if not text:
        return
    buf: List[str] = []
    size = 0
    for word in re.split(r"(\s+)", text):
        if not word:
            continue
        buf.append(word)
        size += len(word)
        if size >= target_chars:
            yield "".join(buf)
            buf = []
            size = 0
    if buf:
        yield "".join(buf)


async def stream_assistant_response(
    module_id: str, body: SendMessageBody
) -> AsyncIterator[str]:
    """Run the plan + tools + narrative inside an SSE generator."""
    ts_start = time.time()
    module_id = _normalise_module_id(module_id)

    # Persist the user message immediately so the thread captures it even if
    # the stream is interrupted.
    user_msg = {"role": "user", "content": body.message, "ts": ts_start}
    with get_session() as session:
        thread = get_or_create_thread(session, module_id)
        thread_id = thread.id
        append_messages(session, thread, [user_msg])

    yield _sse(
        "meta",
        {
            "thread_id": thread_id,
            "module_id": module_id,
            "demo": not bool(os.environ.get("ANTHROPIC_API_KEY")),
            "model": os.environ.get("ANTHROPIC_MODEL", "claude-opus-4-5"),
            "ts": ts_start,
        },
    )

    plan = plan_tool_calls(body.message, default_run_id=body.test_run_id, module_id=module_id)
    tool_results: List[Dict[str, Any]] = []

    # Tool execution happens inside its own DB session so a stuck stream
    # never holds a transaction open. We aggregate results in-memory and
    # persist them with the final assistant message.
    for call in plan:
        yield _sse("tool_call", {"name": call["name"], "args": call["args"]})
        # Run the (sync) DB tool in a worker thread to avoid blocking the loop.
        def _run() -> Dict[str, Any]:
            with get_session() as s:
                return run_tool(s, call["name"], call["args"])
        result = await asyncio.get_event_loop().run_in_executor(None, _run)
        tool_results.append({"name": call["name"], "args": call["args"], "result": result})
        yield _sse("tool_result", {"name": call["name"], "result": result})
        # Small yield so SSE flushes incrementally even on fast tool paths.
        await asyncio.sleep(0)

    narrative = await _build_narrative(body.message, tool_results, module_id)

    streamed: List[str] = []
    for chunk in _chunk_text(narrative):
        streamed.append(chunk)
        yield _sse("token", {"text": chunk})
        await asyncio.sleep(0.01)

    assistant_msg = {
        "role": "assistant",
        "content": narrative,
        "ts": time.time(),
        "tool_calls": [{"name": tr["name"], "args": tr["args"]} for tr in tool_results],
        "tool_results": [{"name": tr["name"], "result": tr["result"]} for tr in tool_results],
    }
    with get_session() as session:
        thread = get_or_create_thread(session, module_id)
        append_messages(session, thread, [assistant_msg])

    yield _sse(
        "done",
        {
            "thread_id": thread_id,
            "elapsed_ms": int((time.time() - ts_start) * 1000),
            "chars": sum(len(s) for s in streamed),
        },
    )


async def _build_narrative(
    message: str, tool_results: List[Dict[str, Any]], module_id: str
) -> str:
    """Synthesize the operator-facing answer.

    Uses Anthropic when ``ANTHROPIC_API_KEY`` is set; otherwise emits a
    deterministic summary derived from tool outputs. Both paths return a
    single string the caller streams as ``token`` events.
    """
    base = _summarise_tool_results(message, tool_results, module_id)
    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        return base

    # Live LLM path — best-effort. Any failure falls back to the deterministic
    # summary so the stream still completes successfully.
    try:
        import httpx  # noqa: WPS433 — local import keeps the module light when unused

        model = os.environ.get("ANTHROPIC_MODEL", "claude-opus-4-5")
        system = (
            "You are the duty PV reliability engineer for the Agnipariksha test "
            "station. Be terse, technical, and reference IEC clauses where relevant. "
            "Use the pre-resolved tool outputs as ground truth — do not invent numbers."
        )
        prompt = (
            f"Module {module_id}.\n\n"
            f"Operator question:\n{message}\n\n"
            f"Tool results (JSON):\n{json.dumps(tool_results, default=str)[:8000]}\n\n"
            "Write 3-6 short bullets summarising what they should know now."
        )
        async with httpx.AsyncClient(timeout=15.0) as client:
            r = await client.post(
                "https://api.anthropic.com/v1/messages",
                headers={
                    "x-api-key": api_key,
                    "anthropic-version": "2023-06-01",
                    "Content-Type": "application/json",
                },
                json={
                    "model": model,
                    "max_tokens": 512,
                    "system": system,
                    "messages": [{"role": "user", "content": prompt}],
                },
            )
            r.raise_for_status()
            data = r.json()
            txt = (data.get("content") or [{}])[0].get("text")
            if isinstance(txt, str) and txt.strip():
                return txt.strip()
    except Exception:
        pass
    return base


# ===========================================================================
# FastAPI router
# ===========================================================================
router = APIRouter(prefix="/api/assistant", tags=["assistant"])


@router.get("/threads/{module_id}", response_model=ThreadOut)
def get_thread(module_id: str = Path(..., min_length=1, max_length=128)) -> ThreadOut:
    module_id = _normalise_module_id(module_id)
    with get_session() as session:
        thread = get_or_create_thread(session, module_id)
        msgs_raw = _ensure_messages_list(thread)
    msgs = [AssistantMessage(**m) for m in msgs_raw if isinstance(m, dict) and "role" in m]
    return ThreadOut(
        module_id=module_id,
        thread_id=thread.id or 0,
        created_at=thread.created_at,
        updated_at=thread.updated_at,
        messages=msgs,
    )


@router.delete("/threads/{module_id}", status_code=204)
def delete_thread(module_id: str = Path(..., min_length=1, max_length=128)) -> None:
    module_id = _normalise_module_id(module_id)
    with get_session() as session:
        if not clear_thread(session, module_id):
            raise HTTPException(status_code=404, detail="thread not found")


@router.post("/threads/{module_id}/messages")
async def post_message(
    body: SendMessageBody,
    module_id: str = Path(..., min_length=1, max_length=128),
) -> StreamingResponse:
    module_id = _normalise_module_id(module_id)

    async def _gen() -> AsyncIterator[str]:
        try:
            async for evt in stream_assistant_response(module_id, body):
                yield evt
        except Exception as exc:  # pragma: no cover - safety net for the SSE stream
            yield _sse("error", {"message": f"{type(exc).__name__}: {exc}"})

    return StreamingResponse(
        _gen(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "X-Accel-Buffering": "no",
            "Connection": "keep-alive",
        },
    )


# Discoverable tool catalogue — handy for the UI and for debugging.
@router.get("/tools")
def list_tools() -> Dict[str, Any]:
    return {
        "tools": [
            {
                "name": "get_run",
                "description": "Fetch a TestRun by id, or recent runs for a module.",
                "args": {
                    "test_run_id": "int (optional)",
                    "module_id": "str (optional)",
                    "limit": "int (default 5)",
                },
            },
            {
                "name": "query_telemetry",
                "description": "Return the last N telemetry samples for a TestRun.",
                "args": {
                    "test_run_id": "int (required)",
                    "last_n": "int (default 20, max 1000)",
                },
            },
            {
                "name": "recompute_analysis",
                "description": "Recompute Gate-2 ΔPmax from telemetry.",
                "args": {"test_run_id": "int (required)"},
            },
            {
                "name": "suggest_pass_fail",
                "description": "Recommend PASS/FAIL with confidence and reason.",
                "args": {"test_run_id": "int (required)"},
            },
        ],
        "gate2_threshold_pct": GATE2_PMAX_DELTA_PERCENT,
    }
