function results = run_psu_step_response()
%RUN_PSU_STEP_RESPONSE Canonical 48 V / 2 A on->off DC-PSU step response.
%   RESULTS = RUN_PSU_STEP_RESPONSE() runs the same 60-tick scenario as the
%   Python backend.app.psu_trace (30 ticks output-ON at 48 V / 2 A, then 30
%   ticks OFF), plots V / I / Tj, and cross-checks the result against
%   matlab/reference_trace.csv generated by the Python model.
%
%   RESULTS is an N-by-5 matrix: [tick, voltage_v, current_a, power_w, temp_c].

    p = psu_plant_defaults();
    state = struct('v', 0.0, 'i', 0.0, 'temp_c', p.ambient_c);

    N = 60; onTicks = 30;
    results = zeros(N, 5);
    for tick = 0:N-1
        on = tick < onTicks;
        sp = struct('output_enabled', on, ...
                    'voltage_v', 48.0 * on, ...
                    'current_a', 2.0 * on);
        [state, r] = psu_plant_step(state, sp, p);
        results(tick+1, :) = [tick, r.voltage_v, r.current_a, r.power_w, r.temperature_c];
    end

    % --- Cross-check against the Python-generated reference -----------------
    csvPath = fullfile(fileparts(mfilename('fullpath')), 'reference_trace.csv');
    if isfile(csvPath)
        ref = readmatrix(csvPath);
        maxErr = max(abs(results(:, 2:5) - ref(:, 2:5)), [], 'all');
        fprintf('Max abs diff vs Python reference: %.3g\n', maxErr);
        assert(maxErr < 1e-3, ...
            'MATLAB plant diverges from Python reference (%.3g >= 1e-3).', maxErr);
        disp('MATLAB plant matches the Python DemoPsuSource reference trace.');
    else
        warning('reference_trace.csv not found; skipping cross-check.');
    end

    % --- Plot ----------------------------------------------------------------
    figure('Name', 'DC-PSU plant step response');
    subplot(3,1,1); plot(results(:,1), results(:,2), 'LineWidth', 1.2);
    ylabel('V_{out} (V)'); grid on;
    title('DC-PSU plant step response (48 V / 2 A: ON ticks 0-29, OFF 30-59)');
    subplot(3,1,2); plot(results(:,1), results(:,3), 'LineWidth', 1.2);
    ylabel('I_{out} (A)'); grid on;
    subplot(3,1,3); plot(results(:,1), results(:,5), 'LineWidth', 1.2);
    ylabel('T_j (\circC)'); xlabel('tick'); grid on;
end
