"""initial schema

Revision ID: d435f3eeb73d
Revises: 
Create Date: 2026-05-12 07:33:24.622189
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = 'd435f3eeb73d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('actor', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('entity', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('entity_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_ts'), ['ts'], unique=False)

    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_tag', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('vendor', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('serial_no', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('last_calibrated_at', sa.DateTime(), nullable=True),
    sa.Column('calibration_due_at', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_equipment_asset_tag'), ['asset_tag'], unique=True)

    op.create_table('module',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serial_no', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('manufacturer', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('pmax_w', sa.Float(), nullable=True),
    sa.Column('voc_v', sa.Float(), nullable=True),
    sa.Column('isc_a', sa.Float(), nullable=True),
    sa.Column('vmpp_v', sa.Float(), nullable=True),
    sa.Column('impp_a', sa.Float(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('module', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_module_serial_no'), ['serial_no'], unique=True)

    op.create_table('operator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('badge_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=320), nullable=True),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('operator', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_operator_badge_id'), ['badge_id'], unique=True)

    op.create_table('spare_part',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('qty_on_hand', sa.Integer(), nullable=False),
    sa.Column('reorder_level', sa.Integer(), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('spare_part', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_spare_part_sku'), ['sku'], unique=True)

    op.create_table('complaint_ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=True),
    sa.Column('customer_ref', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', name='ticketstatus'), nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['module.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('complaint_ticket', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_complaint_ticket_module_id'), ['module_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaint_ticket_status'), ['status'], unique=False)

    op.create_table('maintenance_ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=True),
    sa.Column('opened_by', sa.Integer(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('severity', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', name='ticketstatus'), nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['opened_by'], ['operator.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('maintenance_ticket', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_maintenance_ticket_equipment_id'), ['equipment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_ticket_status'), ['status'], unique=False)

    op.create_table('schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=True),
    sa.Column('equipment_id', sa.Integer(), nullable=True),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('ends_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['module_id'], ['module.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['operator.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schedule_starts_at'), ['starts_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedule_test_type'), ['test_type'], unique=False)

    op.create_table('test_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('csv_path', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('test_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('standard', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('mqt', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'PASSED', 'FAILED', 'STOPPED', 'ABORTED', name='teststatus'), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=True),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('equipment_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['module_id'], ['module.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['operator.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('test_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_run_csv_path'), ['csv_path'], unique=True)
        batch_op.create_index(batch_op.f('ix_test_run_equipment_id'), ['equipment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_run_module_id'), ['module_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_run_operator_id'), ['operator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_run_started_at'), ['started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_run_test_type'), ['test_type'], unique=False)

    op.create_table('ai_thread',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('test_run_id', sa.Integer(), nullable=True),
    sa.Column('messages', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['operator.id'], ),
    sa.ForeignKeyConstraint(['test_run_id'], ['test_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_thread', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_thread_test_run_id'), ['test_run_id'], unique=False)

    op.create_table('barcode_scan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('scanned_by', sa.Integer(), nullable=True),
    sa.Column('test_run_id', sa.Integer(), nullable=True),
    sa.Column('scanned_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['scanned_by'], ['operator.id'], ),
    sa.ForeignKeyConstraint(['test_run_id'], ['test_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('barcode_scan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_barcode_scan_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_barcode_scan_test_run_id'), ['test_run_id'], unique=False)

    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_run_id', sa.Integer(), nullable=True),
    sa.Column('fmt', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('sha256', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('generated_by', sa.Integer(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['generated_by'], ['operator.id'], ),
    sa.ForeignKeyConstraint(['test_run_id'], ['test_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_test_run_id'), ['test_run_id'], unique=False)

    op.create_table('telemetry_sample',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_run_id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('step_no', sa.Integer(), nullable=True),
    sa.Column('voltage', sa.Float(), nullable=True),
    sa.Column('current', sa.Float(), nullable=True),
    sa.Column('power', sa.Float(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['test_run_id'], ['test_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('telemetry_sample', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_telemetry_sample_test_run_id'), ['test_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_telemetry_sample_ts'), ['ts'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('telemetry_sample', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_telemetry_sample_ts'))
        batch_op.drop_index(batch_op.f('ix_telemetry_sample_test_run_id'))

    op.drop_table('telemetry_sample')
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_test_run_id'))

    op.drop_table('report')
    with op.batch_alter_table('barcode_scan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_barcode_scan_test_run_id'))
        batch_op.drop_index(batch_op.f('ix_barcode_scan_code'))

    op.drop_table('barcode_scan')
    with op.batch_alter_table('ai_thread', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_thread_test_run_id'))

    op.drop_table('ai_thread')
    with op.batch_alter_table('test_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_run_test_type'))
        batch_op.drop_index(batch_op.f('ix_test_run_started_at'))
        batch_op.drop_index(batch_op.f('ix_test_run_operator_id'))
        batch_op.drop_index(batch_op.f('ix_test_run_module_id'))
        batch_op.drop_index(batch_op.f('ix_test_run_equipment_id'))
        batch_op.drop_index(batch_op.f('ix_test_run_csv_path'))

    op.drop_table('test_run')
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedule_test_type'))
        batch_op.drop_index(batch_op.f('ix_schedule_starts_at'))

    op.drop_table('schedule')
    with op.batch_alter_table('maintenance_ticket', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_maintenance_ticket_status'))
        batch_op.drop_index(batch_op.f('ix_maintenance_ticket_equipment_id'))

    op.drop_table('maintenance_ticket')
    with op.batch_alter_table('complaint_ticket', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_complaint_ticket_status'))
        batch_op.drop_index(batch_op.f('ix_complaint_ticket_module_id'))

    op.drop_table('complaint_ticket')
    with op.batch_alter_table('spare_part', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_spare_part_sku'))

    op.drop_table('spare_part')
    with op.batch_alter_table('operator', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_operator_badge_id'))

    op.drop_table('operator')
    with op.batch_alter_table('module', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_module_serial_no'))

    op.drop_table('module')
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_equipment_asset_tag'))

    op.drop_table('equipment')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_ts'))
        batch_op.drop_index(batch_op.f('ix_audit_log_action'))

    op.drop_table('audit_log')
    # ### end Alembic commands ###
