#!/usr/bin/env bash
# deploy-staging.sh — Agnipariksha staging deploy preflight (idempotent).
# DRAFT/HOLD: deploy commands are commented out. Uncomment ONLY after
# owner approval. Forces DEMO_MODE=true in any env file it writes.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${REPO_ROOT}/.env.staging"
FRONTEND_DIR="${REPO_ROOT}/frontend"
BACKEND_DIR="${REPO_ROOT}/backend"

log()  { printf '[deploy-staging] %s\n' "$*"; }
fail() { printf '[deploy-staging][ERROR] %s\n' "$*" >&2; exit 1; }

log "Repo root: ${REPO_ROOT}"

# (a) Lint / type checks
if [ -d "${FRONTEND_DIR}" ]; then
    log "Frontend type check (tsc --noEmit)"
    (cd "${FRONTEND_DIR}" && npx --no-install tsc --noEmit) \
        || fail "Frontend tsc failed"
else
    log "WARNING: frontend/ missing, skipping tsc"
fi

if [ -f "${BACKEND_DIR}/main.py" ]; then
    log "Compiling backend/main.py"
    python -m py_compile "${BACKEND_DIR}/main.py" \
        || fail "Backend py_compile failed"
else
    log "WARNING: backend/main.py missing, skipping py_compile"
fi

# (b) Frontend build (no push)
FRONT_BUILD_SIZE="(skipped)"
if [ -d "${FRONTEND_DIR}" ]; then
    log "Building frontend (next build, no deploy)"
    (cd "${FRONTEND_DIR}" && npx --no-install next build) \
        || fail "next build failed"
    [ -d "${FRONTEND_DIR}/.next" ] && \
        FRONT_BUILD_SIZE="$(du -sh "${FRONTEND_DIR}/.next" 2>/dev/null \
            | awk '{print $1}')"
fi

# (c) Force DEMO_MODE=true in any env file we write
log "Writing ${ENV_FILE} (DEMO_MODE=true forced)"
{
    echo "# Generated by scripts/deploy-staging.sh — do not commit."
    echo "DEMO_MODE=true"
    echo "NEXT_PUBLIC_DEMO_MODE=true"
    echo "NEXT_PUBLIC_WS_URL=ws://localhost:8000/ws/live"
} > "${ENV_FILE}"

# Deploy commands intentionally commented out.
log "WARNING: deploy commands are commented — uncomment after owner approval"
log "Would deploy to Vercel staging via 'vercel --target=preview --yes'"
log "Would deploy to Railway via 'railway up'"
# vercel --target=preview --yes
# railway up

# (d) Pre-flight summary
BACK_SIZE="(n/a)"
[ -d "${BACKEND_DIR}" ] && \
    BACK_SIZE="$(du -sh "${BACKEND_DIR}" 2>/dev/null | awk '{print $1}')"

printf '\n====== Agnipariksha staging pre-flight summary ======\n'
printf '  Frontend .next size : %s\n' "${FRONT_BUILD_SIZE}"
printf '  Backend source size : %s\n' "${BACK_SIZE}"
printf '  DEMO_MODE state     : true (forced)\n'
printf '  Env file written    : %s\n' "${ENV_FILE}"
printf '  Deploy commands     : COMMENTED OUT (owner approval required)\n\n'
printf 'Next manual step: review %s, get owner sign-off,\n' "${ENV_FILE}"
printf 'then uncomment the vercel/railway lines in this script.\n'
printf '======================================================\n'

log "Pre-flight complete; no deploy was executed."
