# deploy-staging.ps1 — Agnipariksha staging deploy preflight (idempotent).
# DRAFT/HOLD: deploy commands are commented out. Uncomment ONLY after
# owner approval. Forces DEMO_MODE=true in any env file it writes.

$ErrorActionPreference = 'Stop'

$RepoRoot    = (Resolve-Path -LiteralPath (Join-Path $PSScriptRoot '..')).Path
$EnvFile     = Join-Path $RepoRoot '.env.staging'
$FrontendDir = Join-Path $RepoRoot 'frontend'
$BackendDir  = Join-Path $RepoRoot 'backend'

function Write-Log  { param([string]$m) Write-Host "[deploy-staging] $m" }
function Write-Fail { param([string]$m)
    Write-Host "[deploy-staging][ERROR] $m" -ForegroundColor Red; exit 1 }
function Get-DirSize { param([string]$p)
    if (-not (Test-Path -LiteralPath $p)) { return '(n/a)' }
    $b = (Get-ChildItem -LiteralPath $p -Recurse -File `
        -ErrorAction SilentlyContinue | Measure-Object Length -Sum).Sum
    if ($b) { return ('{0:N1} MB' -f ($b / 1MB)) } else { return '(empty)' } }

Write-Log "Repo root: $RepoRoot"

# (a) Lint / type checks
if (Test-Path -LiteralPath $FrontendDir) {
    Write-Log 'Frontend type check (tsc --noEmit)'
    Push-Location $FrontendDir
    try { npx --no-install tsc --noEmit
          if ($LASTEXITCODE -ne 0) { Write-Fail 'Frontend tsc failed' } }
    finally { Pop-Location }
} else { Write-Log 'WARNING: frontend/ missing, skipping tsc' }

$BackendMain = Join-Path $BackendDir 'main.py'
if (Test-Path -LiteralPath $BackendMain) {
    Write-Log 'Compiling backend/main.py'
    python -m py_compile $BackendMain
    if ($LASTEXITCODE -ne 0) { Write-Fail 'Backend py_compile failed' }
} else { Write-Log 'WARNING: backend/main.py missing, skipping py_compile' }

# (b) Frontend build (no push)
$FrontBuildSize = '(skipped)'
if (Test-Path -LiteralPath $FrontendDir) {
    Write-Log 'Building frontend (next build, no deploy)'
    Push-Location $FrontendDir
    try { npx --no-install next build
          if ($LASTEXITCODE -ne 0) { Write-Fail 'next build failed' } }
    finally { Pop-Location }
    $FrontBuildSize = Get-DirSize (Join-Path $FrontendDir '.next')
}

# (c) Force DEMO_MODE=true in any env file we write
Write-Log "Writing $EnvFile (DEMO_MODE=true forced)"
@(
    '# Generated by scripts/deploy-staging.ps1 — do not commit.',
    'DEMO_MODE=true',
    'NEXT_PUBLIC_DEMO_MODE=true',
    'NEXT_PUBLIC_WS_URL=ws://localhost:8000/ws/live'
) | Set-Content -LiteralPath $EnvFile -Encoding utf8

# Deploy commands intentionally commented out.
Write-Log 'WARNING: deploy commands are commented — uncomment after owner approval'
Write-Log "Would deploy to Vercel staging via 'vercel --target=preview --yes'"
Write-Log "Would deploy to Railway via 'railway up'"
# vercel --target=preview --yes
# railway up

# (d) Pre-flight summary
$BackSize = Get-DirSize $BackendDir
Write-Host ''
Write-Host '====== Agnipariksha staging pre-flight summary ======'
Write-Host ("  Frontend .next size : {0}" -f $FrontBuildSize)
Write-Host ("  Backend source size : {0}" -f $BackSize)
Write-Host  '  DEMO_MODE state     : true (forced)'
Write-Host ("  Env file written    : {0}" -f $EnvFile)
Write-Host  '  Deploy commands     : COMMENTED OUT (owner approval required)'
Write-Host ''
Write-Host ("Next manual step: review {0}, get owner sign-off," -f $EnvFile)
Write-Host  'then uncomment the vercel/railway lines in this script.'
Write-Host  '======================================================'
Write-Log 'Pre-flight complete; no deploy was executed.'
